### ISSUE TITLE
Thrift协议有些问题

### ISSUE THREAD

**Issue by davidaq** [eleme/hackathon_tank#1]
- order的可选项需要补充文档
- assignTank的输入参数类型为list&lt;i32&gt;是不是有问题
- gamestate里的坦克怎么区分敌我

**Comment by ejialan** [comment]
order只有在move的时候不需要dir参数，你可以传任意值进去即可。
因为坦克可以是多辆，所以assignTank的参数是一个列表。
assignTank会传给你自己所拥有的坦克列表，非你自己的坦克就是敌人的，所以你是可以区分敌我的。

**Comment by ejialan** [comment]
idl文件已更新，添加了注释描述你所提到的问题。
