### ISSUE TITLE
[BUG] 战旗生成问题

### ISSUE THREAD

**Issue by inoc603** [eleme/hackathon_tank#17]
https://github.com/eleme/hackathon_tank/blob/master/src/main/java/ele/me/hackathon/tank/GameStateMachine.java#L204

当前仅在坦克移动后判断是否抢到旗，当战旗生成时如果战旗位置上有坦克，战旗不会被夺取。

**Comment by ejialan** [comment]
fixed: 3f5ad1e75ad93888d1e0bb2b6f52563d93cfaab7
