### ISSUE TITLE
evaluateMoveActions 多辆坦克冲突时会有问题

### ISSUE THREAD

**Issue by magygt** [eleme/hackathon_tank#4]
假设三辆坦克 a(1, 1) b(2, 1) c(3, 2)
a 向右移动至 (2, 1)
b 向右移动至 (3, 1)
c 向上移动至 (3, 1)
此时 b c 位置冲突，各自回退，然后从将要移动的坦克 list 中删除。造成 a b 坦克位置冲突。

障碍检测时同样也会遇到这个问题。

**Comment by ejialan** [comment]
的确是的，让我想想怎么修复

**Comment by ejialan** [comment]
fixed in 8e739d9a2eb72e201db4886d0943af0ca046093f
