### ISSUE TITLE
旗子问题

### ISSUE THREAD

**Issue by davidaq** [eleme/hackathon_tank#5]
- 地图参数没有描述，本回合是否有旗子以及旗子隔多久刷新
- 如果3代表旗子的话是否意味着刷旗子的地方不可能有2草丛？
- 第一周的地图没有3是否意味着没旗子？

**Comment by ejialan** [comment]
增加了战旗的生成逻辑
commit f73f07089ad05752b01aaf04e5ca5a646891e4de (HEAD -> master, origin/master)
Author: lanjiangang <jiangang.lan@ele.me>
Date:   Mon Nov 13 16:59:36 2017 +0800

    add logic to generate flag

**Comment by ejialan** [comment]
地图里没有3，只会在最新的状态里标注战旗的位置
