### ISSUE TITLE
坦克互相穿过的问题

### ISSUE THREAD

**Issue by dieyidezui** [eleme/hackathon_tank#6]
两个坦克互相面对面时会直接穿过。
我大概看了一下，判定移动的代码是直接模拟移动到目标点然后判重的，这种case没有考虑到。
不知道是否允许这种情况？

**Comment by ejialan** [comment]
没考虑到😭，容我想想

**Comment by davidaq** [comment]
我之前也写过一个模拟，可以借鉴一下思路，在移动坦克前先做一个set记录不可移动的地方。
value是x,y,direction，所有不移动的坦克当前位置四个direction都加到set。向前移动的当前位置及当前方向加到set，这样就可以用这个set过滤不应该成功的move。

不知道有没有考虑到一个坦克移动失败了以后，可能会链式导致其他坦克移动失败。比如一连串的坦克朝一个方向走，第一个撞墙了，后面的坦克都不能移动成功。

**Comment by inoc603** [comment]
我建议将坦克速度限制为1。
一方面在这个问题上可以简化判断，更重要的是能让选手更专注于策略，而非因坦克速度大于1产生的各种奇怪情况。
速度大于1时，在障碍物附近的移动会变得复杂，加上炮弹先结算的规则，还很容易出现近在咫尺没有障碍却打不到对方的情况。

**Comment by ejialan** [comment]
fixed : 6e2e48bcfad9cc9d0b69d938e993853beb399768
