### ISSUE TITLE
关于可一回合多次操作同一坦克的BUG

### ISSUE THREAD

**Issue by dieyidezui** [eleme/hackathon_tank#9]
![image](https://user-images.githubusercontent.com/11754136/32761119-2de5b208-c8b7-11e7-96b8-760d530ab236.png)

如图所示，上述的测试是可以通过的。
代码中并没有对orders做坦克id的去重。
我的建议是如果发现有重复的坦克id，直接算这回合cheat，所有坦克都不行动。

**Comment by ejialan** [comment]
用户输入校验在PlayerInteract.verifyPlayerInput里
